services:
  - type: web
    name: radar-parser
    runtime: node
    buildCommand: |
      npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "24"
    instanceCount: 1
    instanceType: standard
    healthCheckPath: /
    autoDeploy: true
